exports.data = [
    {
      "assignmentMark": 56,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "ydml4q79zqu8hix",
      "created": "2025-01-23 13:23:56.270Z",
      "examMark": 88,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BBASMGT201402",
          "course_name": "BBA IN STRATEGIC MANAGEMENT",
          "created": "2024-10-10 14:03:16.902Z",
          "duration": "4",
          "facilitator": "lecturer",
          "faculty": "atcth63fb8kki8i",
          "id": "ydml4q79zqu8hix",
          "level": "",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-10-18 13:27:43.253Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-11 07:25:21.269Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "lpoy4g679i2329w",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "PBMGT102",
          "name": "PRINCIPLES OF BUSINESS MANAGEMENT",
          "parent_course": "ydml4q79zqu8hix",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 100,
          "updated": "2024-10-18 13:27:46.636Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "ydml4q79zqu8hix",
          "created": "2025-01-22 09:34:40.541Z",
          "date_of_birth": "2000-02-17 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Boipelo",
          "id": "tnfkll2nmb78c9t",
          "lastname": "Shangano",
          "national_id": "795297523",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "71806244",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "BBA IN STRATEGIC MANAGEMENT",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "81234",
          "updated": "2025-01-22 09:34:40.541Z",
          "user_id": "1yo0movr32s4rbw",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "l9f76ongpcnx71m",
      "lecturerId": "9wby0kxch36sbpd",
      "midSemesterMark": 76,
      "moduleId": "lpoy4g679i2329w",
      "moduleMark": 0,
      "nonCreditAssessments": 88,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "approved",
      "studentId": "tnfkll2nmb78c9t",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:26:09.854Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 65,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "ydml4q79zqu8hix",
      "created": "2025-01-23 13:23:32.905Z",
      "examMark": 87,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BBASMGT201402",
          "course_name": "BBA IN STRATEGIC MANAGEMENT",
          "created": "2024-10-10 14:03:16.902Z",
          "duration": "4",
          "facilitator": "lecturer",
          "faculty": "atcth63fb8kki8i",
          "id": "ydml4q79zqu8hix",
          "level": "",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-10-18 13:27:43.253Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-11 07:25:21.269Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "lpoy4g679i2329w",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "PBMGT102",
          "name": "PRINCIPLES OF BUSINESS MANAGEMENT",
          "parent_course": "ydml4q79zqu8hix",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 100,
          "updated": "2024-10-18 13:27:46.636Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "undefined",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "ydml4q79zqu8hix",
          "created": "2025-01-23 13:05:21.230Z",
          "date_of_birth": "2002-02-21 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Testing",
          "id": "b4rlrlt0d89tsc4",
          "lastname": "Applicant",
          "national_id": "12343213",
          "next_of_kin_name": "Nextof Kin",
          "next_of_kin_number": "76543212",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "BBA IN STRATEGIC MANAGEMENT",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "58747",
          "updated": "2025-01-23 13:05:21.230Z",
          "user_id": "guf45km2pzlaids",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "1cl1qo2skvbam4e",
      "lecturerId": "9wby0kxch36sbpd",
      "midSemesterMark": 78,
      "moduleId": "lpoy4g679i2329w",
      "moduleMark": 78.6,
      "nonCreditAssessments": 71,
      "progressionStatus": "Pass + Proceed",
      "reviewMessage": "",
      "semester": "1",
      "status": "approved",
      "studentId": "b4rlrlt0d89tsc4",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:26:09.857Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 66,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "ydml4q79zqu8hix",
      "created": "2025-01-23 13:22:59.221Z",
      "examMark": 68,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BBASMGT201402",
          "course_name": "BBA IN STRATEGIC MANAGEMENT",
          "created": "2024-10-10 14:03:16.902Z",
          "duration": "4",
          "facilitator": "lecturer",
          "faculty": "atcth63fb8kki8i",
          "id": "ydml4q79zqu8hix",
          "level": "",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-10-18 13:27:43.253Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-11 07:23:51.096Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "1f8ex40f4edgv94",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "STMP131",
          "name": "STRATEGIC MANAGEMENT PRINCIPLES",
          "parent_course": "ydml4q79zqu8hix",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 100,
          "updated": "2024-10-18 13:27:46.344Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "ydml4q79zqu8hix",
          "created": "2025-01-22 09:34:40.541Z",
          "date_of_birth": "2000-02-17 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Boipelo",
          "id": "tnfkll2nmb78c9t",
          "lastname": "Shangano",
          "national_id": "795297523",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "71806244",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "BBA IN STRATEGIC MANAGEMENT",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "81234",
          "updated": "2025-01-22 09:34:40.541Z",
          "user_id": "1yo0movr32s4rbw",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "03ytlrbcamy6yc9",
      "lecturerId": "9wby0kxch36sbpd",
      "midSemesterMark": 78,
      "moduleId": "1f8ex40f4edgv94",
      "moduleMark": 0,
      "nonCreditAssessments": 59,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "pending",
      "studentId": "tnfkll2nmb78c9t",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:23:04.180Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 67,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "ydml4q79zqu8hix",
      "created": "2025-01-23 13:22:30.041Z",
      "examMark": 84,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BBASMGT201402",
          "course_name": "BBA IN STRATEGIC MANAGEMENT",
          "created": "2024-10-10 14:03:16.902Z",
          "duration": "4",
          "facilitator": "lecturer",
          "faculty": "atcth63fb8kki8i",
          "id": "ydml4q79zqu8hix",
          "level": "",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-10-18 13:27:43.253Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-11 07:23:51.096Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "1f8ex40f4edgv94",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "STMP131",
          "name": "STRATEGIC MANAGEMENT PRINCIPLES",
          "parent_course": "ydml4q79zqu8hix",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 100,
          "updated": "2024-10-18 13:27:46.344Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "undefined",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "ydml4q79zqu8hix",
          "created": "2025-01-23 13:05:21.230Z",
          "date_of_birth": "2002-02-21 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Testing",
          "id": "b4rlrlt0d89tsc4",
          "lastname": "Applicant",
          "national_id": "12343213",
          "next_of_kin_name": "Nextof Kin",
          "next_of_kin_number": "76543212",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "BBA IN STRATEGIC MANAGEMENT",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "58747",
          "updated": "2025-01-23 13:05:21.230Z",
          "user_id": "guf45km2pzlaids",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "l8ceied1otednzh",
      "lecturerId": "9wby0kxch36sbpd",
      "midSemesterMark": 88,
      "moduleId": "1f8ex40f4edgv94",
      "moduleMark": 0,
      "nonCreditAssessments": 100,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "pending",
      "studentId": "b4rlrlt0d89tsc4",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:23:04.183Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 98,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "ydml4q79zqu8hix",
      "created": "2025-01-23 13:21:51.551Z",
      "examMark": 89,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BBASMGT201402",
          "course_name": "BBA IN STRATEGIC MANAGEMENT",
          "created": "2024-10-10 14:03:16.902Z",
          "duration": "4",
          "facilitator": "lecturer",
          "faculty": "atcth63fb8kki8i",
          "id": "ydml4q79zqu8hix",
          "level": "",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-10-18 13:27:43.253Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 40,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-10 14:10:55.050Z",
          "credits": 10,
          "exam_weight": 40,
          "facilitator": "Mike Modise",
          "faculty": "atcth63fb8kki8i",
          "id": "xxlgk0m4bdi9kt9",
          "is_prerequisite": false,
          "location": "Gaborone",
          "mid_semester_weight": 40,
          "minimum_pass_grade": 0,
          "module_code": "IBC112",
          "name": "BUSINESS COMMUNICATION",
          "parent_course": "ydml4q79zqu8hix",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 30,
          "updated": "2024-10-21 12:49:20.165Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "ydml4q79zqu8hix",
          "created": "2025-01-22 09:34:40.541Z",
          "date_of_birth": "2000-02-17 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Boipelo",
          "id": "tnfkll2nmb78c9t",
          "lastname": "Shangano",
          "national_id": "795297523",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "71806244",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "BBA IN STRATEGIC MANAGEMENT",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "81234",
          "updated": "2025-01-22 09:34:40.541Z",
          "user_id": "1yo0movr32s4rbw",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "o6qiylszkyhferi",
      "lecturerId": "9wby0kxch36sbpd",
      "midSemesterMark": 79,
      "moduleId": "xxlgk0m4bdi9kt9",
      "moduleMark": 0,
      "nonCreditAssessments": 90,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "pending",
      "studentId": "tnfkll2nmb78c9t",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:21:56.560Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 70,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "ydml4q79zqu8hix",
      "created": "2025-01-23 13:21:24.424Z",
      "examMark": 79,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BBASMGT201402",
          "course_name": "BBA IN STRATEGIC MANAGEMENT",
          "created": "2024-10-10 14:03:16.902Z",
          "duration": "4",
          "facilitator": "lecturer",
          "faculty": "atcth63fb8kki8i",
          "id": "ydml4q79zqu8hix",
          "level": "",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-10-18 13:27:43.253Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 40,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-10 14:10:55.050Z",
          "credits": 10,
          "exam_weight": 40,
          "facilitator": "Mike Modise",
          "faculty": "atcth63fb8kki8i",
          "id": "xxlgk0m4bdi9kt9",
          "is_prerequisite": false,
          "location": "Gaborone",
          "mid_semester_weight": 40,
          "minimum_pass_grade": 0,
          "module_code": "IBC112",
          "name": "BUSINESS COMMUNICATION",
          "parent_course": "ydml4q79zqu8hix",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 30,
          "updated": "2024-10-21 12:49:20.165Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "undefined",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "ydml4q79zqu8hix",
          "created": "2025-01-23 13:05:21.230Z",
          "date_of_birth": "2002-02-21 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Testing",
          "id": "b4rlrlt0d89tsc4",
          "lastname": "Applicant",
          "national_id": "12343213",
          "next_of_kin_name": "Nextof Kin",
          "next_of_kin_number": "76543212",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "BBA IN STRATEGIC MANAGEMENT",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "58747",
          "updated": "2025-01-23 13:05:21.230Z",
          "user_id": "guf45km2pzlaids",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "ujj7b0nc30nehda",
      "lecturerId": "9wby0kxch36sbpd",
      "midSemesterMark": 75,
      "moduleId": "xxlgk0m4bdi9kt9",
      "moduleMark": 0,
      "nonCreditAssessments": 90,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "pending",
      "studentId": "b4rlrlt0d89tsc4",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:21:56.566Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 75,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-23 13:19:56.791Z",
      "examMark": 89,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:10:50.009Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "q9vroqmonuzdwtz",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IIT114",
          "name": "INTRODUCTION TO INFORMATION TECHNOLOGY",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:10:50.009Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-21 12:19:59.034Z",
          "date_of_birth": "2000-02-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Les ",
          "id": "l1lat9mpu18u4j9",
          "lastname": "Tsame",
          "national_id": "32145789",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "73214567",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "14785",
          "updated": "2025-01-21 12:19:59.034Z",
          "user_id": "6pe88thmuf4z1ak",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "91nn04we084sgck",
      "lecturerId": "9wby0kxch36sbpd",
      "midSemesterMark": 88,
      "moduleId": "q9vroqmonuzdwtz",
      "moduleMark": 0,
      "nonCreditAssessments": 90,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "pending",
      "studentId": "l1lat9mpu18u4j9",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:19:59.195Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 75,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-23 13:19:41.021Z",
      "examMark": 89,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:10:50.009Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "q9vroqmonuzdwtz",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IIT114",
          "name": "INTRODUCTION TO INFORMATION TECHNOLOGY",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:10:50.009Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-22 08:53:31.492Z",
          "date_of_birth": "2007-01-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Tsame",
          "id": "zgugcg99pfktd56",
          "lastname": "Les",
          "national_id": "02314567",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "74550506",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "123780",
          "updated": "2025-01-22 08:53:31.492Z",
          "user_id": "3m5fa8p9vee3qv7",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "mqj7psf849j5f1o",
      "lecturerId": "9wby0kxch36sbpd",
      "midSemesterMark": 88,
      "moduleId": "q9vroqmonuzdwtz",
      "moduleMark": 0,
      "nonCreditAssessments": 90,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "pending",
      "studentId": "zgugcg99pfktd56",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:19:59.300Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 75,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-23 08:54:12.823Z",
      "examMark": 89,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:11:48.779Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "lxi56xr90ybbcsi",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IENT 125",
          "name": "INTRODUCTION TO ENTREPRENEURSHIP",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "breb54pekxj0czs",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:11:48.779Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-21 12:19:59.034Z",
          "date_of_birth": "2000-02-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Les ",
          "id": "l1lat9mpu18u4j9",
          "lastname": "Tsame",
          "national_id": "32145789",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "73214567",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "14785",
          "updated": "2025-01-21 12:19:59.034Z",
          "user_id": "6pe88thmuf4z1ak",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "snm2llww7dqlwzv",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 88,
      "moduleId": "lxi56xr90ybbcsi",
      "moduleMark": 84.6,
      "nonCreditAssessments": 90,
      "progressionStatus": "Pass + Proceed",
      "reviewMessage": "",
      "semester": "1",
      "status": "approved",
      "studentId": "l1lat9mpu18u4j9",
      "supplementaryMark": 0,
      "updated": "2025-01-23 08:54:39.379Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 75,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-23 08:53:16.625Z",
      "examMark": 75,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:11:48.779Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "lxi56xr90ybbcsi",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IENT 125",
          "name": "INTRODUCTION TO ENTREPRENEURSHIP",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "breb54pekxj0czs",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:11:48.779Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-22 08:53:31.492Z",
          "date_of_birth": "2007-01-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Tsame",
          "id": "zgugcg99pfktd56",
          "lastname": "Les",
          "national_id": "02314567",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "74550506",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "123780",
          "updated": "2025-01-22 08:53:31.492Z",
          "user_id": "3m5fa8p9vee3qv7",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "1ddqecvypwadbjv",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 88,
      "moduleId": "lxi56xr90ybbcsi",
      "moduleMark": 77.6,
      "nonCreditAssessments": 0,
      "progressionStatus": "Pass + Proceed",
      "reviewMessage": "",
      "semester": "1",
      "status": "approved",
      "studentId": "zgugcg99pfktd56",
      "supplementaryMark": 0,
      "updated": "2025-01-23 08:54:39.423Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 75,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-21 12:25:52.843Z",
      "examMark": 89,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:13:13.719Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "alupshqk5b1ax8k",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "CSP121",
          "name": "CUSTOMER SERVICE PRINCIPLES",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "breb54pekxj0czs",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:13:13.719Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-21 12:19:59.034Z",
          "date_of_birth": "2000-02-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Les ",
          "id": "l1lat9mpu18u4j9",
          "lastname": "Tsame",
          "national_id": "32145789",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "73214567",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "14785",
          "updated": "2025-01-21 12:19:59.034Z",
          "user_id": "6pe88thmuf4z1ak",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "selsfuqs4rsf2y2",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 88,
      "moduleId": "alupshqk5b1ax8k",
      "moduleMark": 0,
      "nonCreditAssessments": 90,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "approved",
      "studentId": "l1lat9mpu18u4j9",
      "supplementaryMark": 0,
      "updated": "2025-01-23 08:52:21.284Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 73,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-21 09:48:49.264Z",
      "examMark": 70,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:11:48.779Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "lxi56xr90ybbcsi",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IENT 125",
          "name": "INTRODUCTION TO ENTREPRENEURSHIP",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "breb54pekxj0czs",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:11:48.779Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2024-12-10 13:59:16.315Z",
          "date_of_birth": "2000-02-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Thabang",
          "id": "jswwp16c2g1vsgu",
          "lastname": "Brandon",
          "national_id": "147852369",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "74550506",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "789456127",
          "updated": "2025-01-16 08:58:09.170Z",
          "user_id": "68end2dpjays9p0",
          "year_of_study": "Year 2"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "ncrh6c01sdc7wl7",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 75,
      "moduleId": "lxi56xr90ybbcsi",
      "moduleMark": 71.9,
      "nonCreditAssessments": 88,
      "progressionStatus": "Pass + Proceed",
      "reviewMessage": "",
      "semester": "1",
      "status": "approved",
      "studentId": "jswwp16c2g1vsgu",
      "supplementaryMark": 0,
      "updated": "2025-01-23 08:54:39.422Z",
      "yearOfStudy": 2
    },
    {
      "assignmentMark": 71,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-21 09:48:17.899Z",
      "examMark": 81,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:11:48.779Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "lxi56xr90ybbcsi",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IENT 125",
          "name": "INTRODUCTION TO ENTREPRENEURSHIP",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "breb54pekxj0czs",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:11:48.779Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-21 07:58:26.017Z",
          "date_of_birth": "2000-02-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Khumo",
          "id": "cz65l4auy9ybgn9",
          "lastname": "Talib",
          "national_id": "109876567",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "78454545",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "36985",
          "updated": "2025-01-21 07:58:26.017Z",
          "user_id": "ab6jlxnr7b487xe",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "q4tjp763ywbva2n",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 69,
      "moduleId": "lxi56xr90ybbcsi",
      "moduleMark": 75.6,
      "nonCreditAssessments": 80,
      "progressionStatus": "Pass + Proceed",
      "reviewMessage": "",
      "semester": "1",
      "status": "approved",
      "studentId": "cz65l4auy9ybgn9",
      "supplementaryMark": 0,
      "updated": "2025-01-23 08:54:39.333Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 75,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-21 09:47:48.745Z",
      "examMark": 95,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:11:48.779Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "lxi56xr90ybbcsi",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IENT 125",
          "name": "INTRODUCTION TO ENTREPRENEURSHIP",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "breb54pekxj0czs",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:11:48.779Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-21 07:58:35.190Z",
          "date_of_birth": "2000-03-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Shangano",
          "id": "ivanp50bp72dg0d",
          "lastname": "Baebele",
          "national_id": "58964712",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "78945600",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "12378",
          "updated": "2025-01-21 07:58:35.190Z",
          "user_id": "cvlzvofjw1w20dh",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "67dps8ui0qnq3tl",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 75,
      "moduleId": "lxi56xr90ybbcsi",
      "moduleMark": 85,
      "nonCreditAssessments": 100,
      "progressionStatus": "Pass + Proceed",
      "reviewMessage": "",
      "semester": "1",
      "status": "approved",
      "studentId": "ivanp50bp72dg0d",
      "supplementaryMark": 0,
      "updated": "2025-01-23 08:54:39.434Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 75,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-21 09:47:27.734Z",
      "examMark": 90,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:11:48.779Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "lxi56xr90ybbcsi",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IENT 125",
          "name": "INTRODUCTION TO ENTREPRENEURSHIP",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "breb54pekxj0czs",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:11:48.779Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-21 07:58:42.904Z",
          "date_of_birth": "2000-02-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Thabiso",
          "id": "ee6o28nwodinlo1",
          "lastname": "Western",
          "national_id": "25874136",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "71806233",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "12345",
          "updated": "2025-01-21 07:58:42.904Z",
          "user_id": "czur6pvwfmnulfa",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "8miqqto7gscsdns",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 80,
      "moduleId": "lxi56xr90ybbcsi",
      "moduleMark": 83.5,
      "nonCreditAssessments": 80,
      "progressionStatus": "Pass + Proceed",
      "reviewMessage": "",
      "semester": "1",
      "status": "approved",
      "studentId": "ee6o28nwodinlo1",
      "supplementaryMark": 0,
      "updated": "2025-01-23 08:54:39.365Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 95,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-21 09:47:10.028Z",
      "examMark": 89,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:11:48.779Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "lxi56xr90ybbcsi",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IENT 125",
          "name": "INTRODUCTION TO ENTREPRENEURSHIP",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "breb54pekxj0czs",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:11:48.779Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-21 07:58:52.614Z",
          "date_of_birth": "2000-02-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Tumelo ",
          "id": "sc8ubd2zdyp65oe",
          "lastname": "Makgoa",
          "national_id": "78945612",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "74550506",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "14785",
          "updated": "2025-01-21 07:58:52.614Z",
          "user_id": "6wtz46lvfnoxzqr",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "od5yl3jnsrqxmwo",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 99,
      "moduleId": "lxi56xr90ybbcsi",
      "moduleMark": 92.8,
      "nonCreditAssessments": 100,
      "progressionStatus": "Pass + Proceed",
      "reviewMessage": "",
      "semester": "1",
      "status": "approved",
      "studentId": "sc8ubd2zdyp65oe",
      "supplementaryMark": 0,
      "updated": "2025-01-23 08:54:39.378Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 73,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-21 09:46:26.164Z",
      "examMark": 88,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:10:50.009Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "q9vroqmonuzdwtz",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IIT114",
          "name": "INTRODUCTION TO INFORMATION TECHNOLOGY",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:10:50.009Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2024-12-10 13:59:16.315Z",
          "date_of_birth": "2000-02-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Thabang",
          "id": "jswwp16c2g1vsgu",
          "lastname": "Brandon",
          "national_id": "147852369",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "74550506",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "789456127",
          "updated": "2025-01-16 08:58:09.170Z",
          "user_id": "68end2dpjays9p0",
          "year_of_study": "Year 2"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "oxmsu03t3zqo20o",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 45,
      "moduleId": "q9vroqmonuzdwtz",
      "moduleMark": 0,
      "nonCreditAssessments": 88,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "pending",
      "studentId": "jswwp16c2g1vsgu",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:19:59.268Z",
      "yearOfStudy": 2
    },
    {
      "assignmentMark": 78,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-21 09:46:03.448Z",
      "examMark": 89,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:10:50.009Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "q9vroqmonuzdwtz",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IIT114",
          "name": "INTRODUCTION TO INFORMATION TECHNOLOGY",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:10:50.009Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-21 07:58:26.017Z",
          "date_of_birth": "2000-02-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Khumo",
          "id": "cz65l4auy9ybgn9",
          "lastname": "Talib",
          "national_id": "109876567",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "78454545",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "36985",
          "updated": "2025-01-21 07:58:26.017Z",
          "user_id": "ab6jlxnr7b487xe",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "dlszvlwal66u16h",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 78,
      "moduleId": "q9vroqmonuzdwtz",
      "moduleMark": 0,
      "nonCreditAssessments": 98,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "pending",
      "studentId": "cz65l4auy9ybgn9",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:19:59.287Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 59,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-21 09:45:37.928Z",
      "examMark": 65,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:10:50.009Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "q9vroqmonuzdwtz",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IIT114",
          "name": "INTRODUCTION TO INFORMATION TECHNOLOGY",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:10:50.009Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-21 07:58:35.190Z",
          "date_of_birth": "2000-03-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Shangano",
          "id": "ivanp50bp72dg0d",
          "lastname": "Baebele",
          "national_id": "58964712",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "78945600",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "12378",
          "updated": "2025-01-21 07:58:35.190Z",
          "user_id": "cvlzvofjw1w20dh",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "3jlnekucj02yx4b",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 47,
      "moduleId": "q9vroqmonuzdwtz",
      "moduleMark": 0,
      "nonCreditAssessments": 55,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "pending",
      "studentId": "ivanp50bp72dg0d",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:19:59.304Z",
      "yearOfStudy": 1
    },
    {
      "assignmentMark": 69,
      "collectionId": "i44cgy5ck082hwg",
      "collectionName": "results",
      "courseId": "50uvzomc30xggft",
      "created": "2025-01-21 09:45:11.089Z",
      "examMark": 74,
      "expand": {
        "courseId": {
          "centre_location": "Gaborone",
          "collectionId": "dfjzrcuxm1wk64u",
          "collectionName": "courses",
          "course_code": "BCOMENT201502",
          "course_name": "B.COM IN ENTERPRENEURSHIP",
          "created": "2024-10-10 13:23:35.190Z",
          "duration": "4",
          "facilitator": "Thabiso",
          "faculty": "atcth63fb8kki8i",
          "id": "50uvzomc30xggft",
          "level": "1",
          "sponsorship_options": "All",
          "total_credits": 120,
          "type": "Bachelor Degree",
          "updated": "2024-11-25 13:10:45.622Z"
        },
        "facultyId": {
          "collectionId": "vrzzud8rfb14ubk",
          "collectionName": "faculties",
          "created": "2023-11-21 10:34:40.889Z",
          "facilitator": "qb159mq7oroiifn",
          "id": "atcth63fb8kki8i",
          "name": "Management Faculty",
          "updated": "2024-11-28 16:05:18.864Z"
        },
        "moduleId": {
          "assignment_weight": 100,
          "collectionId": "1mh3ljjdldgb83m",
          "collectionName": "modules",
          "created": "2024-10-23 09:10:50.009Z",
          "credits": 10,
          "exam_weight": 100,
          "facilitator": "",
          "faculty": "atcth63fb8kki8i",
          "id": "q9vroqmonuzdwtz",
          "is_prerequisite": false,
          "location": "",
          "mid_semester_weight": 100,
          "minimum_pass_grade": 0,
          "module_code": "IIT114",
          "name": "INTRODUCTION TO INFORMATION TECHNOLOGY",
          "parent_course": "50uvzomc30xggft",
          "prerequisites": [],
          "semester": "8xdeo7eoi8gg2br",
          "supplement_weight": 100,
          "updated": "2024-10-23 09:10:50.009Z",
          "year_level": 1
        },
        "studentId": {
          "accomo": "true",
          "collectionId": "lq6w0gpli2zjcih",
          "collectionName": "students",
          "country": "Botswana",
          "course_id": "50uvzomc30xggft",
          "created": "2025-01-21 07:58:42.904Z",
          "date_of_birth": "2000-02-15 00:00:00.000Z",
          "dtefStatus": false,
          "dtef_status": "pending",
          "firstname": "Thabiso",
          "id": "ee6o28nwodinlo1",
          "lastname": "Western",
          "national_id": "25874136",
          "next_of_kin_name": "NextKIN",
          "next_of_kin_number": "71806233",
          "phoneNumber": "74550506",
          "phone_number": 0,
          "physical_address": "",
          "prog_name": "B.COM IN ENTERPRENEURSHIP",
          "program_code": "",
          "reg_status": "approved",
          "relationship": "Mother",
          "semester_id": "55erro2en14px6u",
          "sponsor": "Government Regular",
          "status": "",
          "studentNo": "",
          "study_mode": "Full time",
          "title": "",
          "tr_number": "12345",
          "updated": "2025-01-21 07:58:42.904Z",
          "user_id": "czur6pvwfmnulfa",
          "year_of_study": "Year 1"
        }
      },
      "facultyId": "atcth63fb8kki8i",
      "id": "etx5rpomuv2v0pu",
      "lecturerId": "4rw8ima60kyyt8t",
      "midSemesterMark": 74,
      "moduleId": "q9vroqmonuzdwtz",
      "moduleMark": 0,
      "nonCreditAssessments": 88,
      "progressionStatus": "",
      "reviewMessage": "",
      "semester": "1",
      "status": "pending",
      "studentId": "ee6o28nwodinlo1",
      "supplementaryMark": 0,
      "updated": "2025-01-23 13:19:59.294Z",
      "yearOfStudy": 1
    }
  ]